apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-webapp-saturador
spec:
  replicas: 60            # En 60 sufciiente, si necesitas más carga no sea malo 
  selector:
    matchLabels:
      app: aws-webapp-saturador
  template:
    metadata:
      labels:
        app: aws-webapp-saturador
    spec:
      containers:
        - name: sat
          image: busybox:1.36
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          command: ["/bin/sh","-c"]
          args:
            - |
              WORKERS=${WORKERS:-20}
              URL=${TARGET_URL:-http://aws-webapp-service.default.svc.cluster.local}
              for i in $(seq 1 $WORKERS); do
                (while true; do wget -q -O- "$URL" > /dev/null; done) &
              done
              wait
          env:
            - name: TARGET_URL
              value: "http://aws-webapp-service.default.svc.cluster.local"
            - name: WORKERS
              value: "20"
